name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]  # or master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'biomechanics'  # THIS is the folder to publish

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4